### ISSUE TITLE
fragattack driver build issue on Jetson Nano (4.9 Kernel)

### ISSUE THREAD

**Issue by soylentgreen** [vanhoefm/fragattacks-drivers58#2]
It doesn't seem possible to build the fragattack driver patches on the jetson nano, it run the NVIDIA custom L4T 4.9 kernel on Ubuntu 18.04. 
it was also tested on 20.04 (with the same 4.9 kernel) and error's on the same build points. 
I've attached the system configuration, make error file and make output. it appears the driver pack may be for kernel 5+? 
```
make[6]: *** No rule to make target '/home/ubuntu/fragattacks/fragattacks-drivers58/compat/verification/pkcs7.asn1.o', needed by '/home/ubuntu/fragattacks/fragattacks-drivers58/compat/compat.o'.  Stop.
make[6]: *** Waiting for unfinished jobs....
make[5]: *** [/home/ubuntu/fragattacks/fragattacks-drivers58/compat] Error 2
make[5]: *** Waiting for unfinished jobs....
make[4]: *** [_module_/home/ubuntu/fragattacks/fragattacks-drivers58] Error 2
```

[SYSTEM_CONFIG.txt](https://github.com/vanhoefm/fragattacks-drivers58/files/7360069/SYSTEM_CONFIG.txt)
[error.log](https://github.com/vanhoefm/fragattacks-drivers58/files/7360065/error.log)
[output.log](https://github.com/vanhoefm/fragattacks-drivers58/files/7360066/output.log)

**Comment by vanhoefm** [comment]
Can you double-check that you installed all dependencies and made a full clone of the repository?

**Comment by soylentgreen** [comment]
replicating it again with a new clone, but it does appear to be a full clone.
the only dependency that isn't direct is the linux headers, the nvidia package uses custom headers. 

```
ubuntu@jetson-nano:~$ uname -a
Linux jetson-nano 4.9.253-tegra #1 SMP PREEMPT Mon Jul 26 12:13:06 PDT 2021 aarch64 aarch64 aarch64 GNU/Linux

ubuntu@jetson-nano:~$ uname -r
4.9.253-tegra

```

**Comment by soylentgreen** [comment]
these are the headers currently on system. 
```
ubuntu@jetson-nano:~$ /usr/src/linux-headers-
linux-headers-4.15.0-159/
linux-headers-4.15.0-159-generic/
linux-headers-4.9.140-tegra-linux_x86_64/
linux-headers-4.9.140-tegra-ubuntu18.04_aarch64/
linux-headers-4.9.253-tegra-ubuntu18.04_aarch64/
linux-headers-5.4.0-87-generic/

ubuntu@jetson-nano:/lib/modules$ ls
4.15.0-159-generic  4.9.140-tegra  4.9.253-tegra  5.4.0-87-generic
```
run again with the reclone, appears to be still an issue
[error.log](https://github.com/vanhoefm/fragattacks-drivers58/files/7360123/error.log)
[main.log](https://github.com/vanhoefm/fragattacks-drivers58/files/7360124/main.log)

**Comment by vanhoefm** [comment]
I don't know why this doesn't work. If you managed to fix this, please post your steps here on how you fixed it. I'm closing this for now.
