### ISSUE TITLE
drivers/net/wireless/ath9k/init.c missing parameter

### ISSUE THREAD

**Issue by cerferlo** [vanhoefm/fragattacks-drivers58#3]
on Ubuntu 21.10, the following error is given after the command "make" is given:

`fragattacks-drivers58/drivers/net/wireless/ath/ath9k/init.c: In function ‘ath9k_of_init’:`

`fragattacks-drivers58/drivers/net/wireless/ath/ath9k/init.c:643:15: error: too few arguments to function ‘of_get_mac_address’
  643 |         mac = of_get_mac_address(np);`
`      |               ^~~~~~~~~~~~~~~~~~`

`In file included from /fragattacks-drivers58/backport-include/linux/of_net.h:3, from /fragattacks-drivers58/drivers/net/wireless/ath/ath9k/init.c:24:`

`./include/linux/of_net.h:25:19: note: declared here`
`   25 | static inline int of_get_mac_address(struct device_node *np, u8 *mac)`
`      |                   ^~~~~~~~~~~~~~~~~~`

**Comment by vanhoefm** [comment]
Ubuntu 21.10 is using a kernel version that is not supported by the tool. Only kernels below or equal to 5.12 are supported. I've [updated the README](https://github.com/vanhoefm/fragattacks#id-prerequisites) to explain this. The README now also contains an example of how to install an older kernel on Ubuntu 20.04 that is supported. On Ubuntu 21.10 you can hopefully manually installed an older supported kernel in a similar manner.
